### ISSUE TITLE
Adding specific filename

### ISSUE THREAD

**Issue by nelsieborja** [beshanoe/mini-css-extract-plugin-with-rtl#2]
Is it possible to add specific filename for both EN and AR file eg:
`app-en.css` for EN
`app-ar.css` for AR

Also sourcemap is not working..

Thanks! Great plugin ^^

**Comment by beshanoe** [comment]
@nelsieborja hi, currently the plugin supports only the cases where the filename generated by `WebpackRTLPlugin` is the same as one generated by `MiniCSSExtractPlugin` with extension changed from `.css` to `.rtl.css`. I'm thinking about a better solution now. Ideally, it should work like this:
For each of the `.css` file processed by `WebpackRTLPlugin` the mapping should be created and stored in the runtime chunk, so it won't depend on `.rtl.css` naming convention. But the problem now is that AFAIK at the stage of generating RTL CSS(`emit` stage), there's no possibility of injecting anything into the runtime template code(at least without heavy hacking). 
I'll try to figure it out, cause now the only idea I have is to generate something like `rtl-manifest.json`(should be implemented in `WebpackRTLPlugin) which could look like
```json
{
  "1.chunk.44afe0c.css": "1.chunk-rtl.8f4897.css",
  "lazyComponent.chunk.6e9baf.css": "2.chunk-rtl.fe0e9b.css"
}
```
And it will be loaded and cached at the first time an async CSS chunk is loaded.

Regarding sourcemaps, not sure that the issue is in this fork. Anyway, it would be nice if you share more details or examples of what you're trying to achieve. Because from the filenames you've provided it's completely unclear if you have async chunks at all and if you have separate css for each language
